{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-feature-table
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-bio {{ scikit_bio }}
    - biom-format {{ biom_format }}
    - seaborn {{ seaborn }}
    - matplotlib {{ matplotlib }}
    - pandas {{ pandas }}
    - numpy
    # `ipywidgets` included to avoid ShimWarning from
    # `seaborn` imports:
    #  https://github.com/mwaskom/seaborn/issues/874
    - ipywidgets
    - qiime2 {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - selenium

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2templates >={{ q2templates }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_feature_table
    - qiime2.plugins.feature_table

  commands:
    - py.test --pyargs q2_feature_table

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
